version: "2"
services:
    client:
        build: ./client
        restart: always
        container_name: mudclient
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        depends_on:
            - aptmud
        links:
            - aptmud
        networks:
            - frontnet
    aptmud:
        build: ./
        container_name: aptmud
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - .:/aptmud
            - /node_modules
        depends_on:
            - mongodb
            - redis
        networks:
            - frontnet
            - backnet
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - "27017:27017"
        command: mongod --noauth
        networks:
            - backnet
    redis:
        image: redis
        container_name: redis-container
        ports:
            - "6379:6379"
        expose:
            - 6379
        networks:
            - backnet
networks:
    frontnet:
        driver: bridge
    backnet:
        driver: bridge
