const { mongoDbClientConnect } = require("../../backendFunctions/mongoHelpers")

async function getAllUserIdsInRoom(client, roomName) {
    /**
     * Gets an array of all userIds in a room db
     * @param {String} roomName - Name of the room db
     * @returns Array of userIds
     */
    const database = client.db(roomName)
    const usersObjList = await database.collection('people').find().toArray()
    const userNamesList = usersObjList.map((user) => {return String(user.userId)})

    return userNamesList
}

async function getUserDbIdByUserId(client, userId) {
    /**
     * Takes a user ID string and return the userDbID associated with in in the userIdMap db
     * @param {String} userId - String of the userid (generated by browser)
     * @return {String} String of the user DB Id. NOT an ObjectId object
     */
    const database =  client.db("userIdMap")
    const collection = database.collection('usermapids')
    let x = await collection.findOne({ userId: userId })
    // maybe add a retry here in the future
    return x.userDbId
}

async function getUserIdByUserDbId(client, userDbId) {
    /**
     * Takes a user DB ID string and return the user ID associated with in in the userIdMap db
     * @param {String} userDbId - String of the userid (generated by browser)
     * @return {String} String of the user DB Id. NOT an ObjectId object
     */
    const database = client.db("userIdMap")
    const collection = database.collection('usermapids')
    let x = await collection.findOne({ userDbId: userDbId })
    return x.userId
}

async function getUserMapObjByUserId(client, userId) {
    /**
     * Gets the user map object when provided a userId
     * @param {String} userId - user id of the user. Makes sense
     * @return - user map obj. this one is pretty straightforward 
     */
    const database = client.db("userIdMap")
    const collection = database.collection('usermapids')
    let x = await collection.findOne({ userId: userId })
    return x
}

async function getUserRoomByUserId(client, userId) {
    /**
     * Takes a user ID string and return the roomName associated with
     * @param {String} userId: String of the userid (generated by browser)
     * @return {String} String of the user room. This should be a database name
     */
    const database = client.db("userIdMap")
    const collection = database.collection('usermapids')
    let x = await collection.findOne({ userId: userId })
    return x.userRoom
}

async function getUserRoomFriendlyNameByUserId(client, userId) {
    /**
     * Takes a user ID string and return the friend room name
     * @param {String} userId: String of the userid (generated by browser)
     * @return {String} String of the user room. This should be a database name
     */
    const database = client.db("userIdMap")
    const collection = database.collection('usermapids')
    let x = await collection.findOne({ userId: userId })
    
    return x.userRoom
}

async function getUserNameByUserId (client, userId) {
    /**
     * Gets the username (first entry in .names) of a user by userId
     * @param {String} userId - userid of the user
     * @return {String} user name of the matching user
     */
    const database = client.db("userIdMap")
    const collection = database.collection('usermapids')
    let x = await collection.findOne({ userId: userId })
    return x.userName
}

module.exports = {
    getAllUserIdsInRoom,
    getUserDbIdByUserId,
    getUserIdByUserDbId,
    getUserMapObjByUserId,
    getUserNameByUserId,
    getUserRoomByUserId,
    getUserRoomFriendlyNameByUserId
}
